- name: nginx
  hosts: all
  become: yes
  tasks:
   - name: Remove the nginx package
     ansible.builtin.dnf:
      name: httpd
      state: absent

   - name: Install the latest version of Apache
     ansible.builtin.dnf:
      name: nginx
      state: latest

   - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes