- name: multiplay
  hosts: localhost
  become: yes
  tasks:
   - name: print msg
     ansible.builtin.debug:
      msg: "hi how is yours perparation"

   - name: print msg
     ansible.builtin.debug:
      msg: "hi for debops!!!! my perparation is good"

    