- name: declare varibales
  hosts: localhost
  become: yes
  tasks:
    - name: print variables 
      vars_files:
        - vars.yaml
      ansible.builtin.debug:
         msg: hi this {{name}} with age of {{age}} upgrading my skills for {{course}}jobs