- name: declare varibales
  hosts: localhost
  vars_files:
    - vars.yaml
  become: yes
  tasks:
    - name: print variables 
      ansible.builtin.debug:
         msg: hi this {{name}} with age of {{age}} upgrading my skills for {{course}}jobs